<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

 /** Zakir Added. Replace the home loop with our custom **/
 remove_action( 'genesis_loop', 'genesis_do_loop' );
 add_action( 'genesis_loop', 'blog_custom_loop' );

 /** Custom  loop **/
 function blog_custom_loop() {
 	?>
     <div class="pt-24 pb-10 px-6 md:py-32 md:mt-24 overflow-hidden">

         <div class="md:container md:mx-auto">
             <h2 class="font-bold text-heading1 text-gray-900 uppercase md:text-h2">
                 Blog
             </h2>

             <div class="mt-8 md:mt-16 md:mx-auto ">

 	            <?php blog_filter_view(); ?>

             </div>

         </div>

         <div class="post-items md:mt-10">
             <div class="md:container md:mx-auto">
 			<?php
 			$count = 0;
 			$html = '';

 			while ( have_posts() ) :
 			the_post();

 			$sticky_post = has_term('14', 'category', get_the_ID() );
 			?>

                 <?php
                     if( $sticky_post && $count == 0 ){

 	                    get_template_part( 'template-parts/taxonomy/taxonomy-featured', get_post_type() );

 	                    $count++;

                     }else{

                         ob_start();

                         get_template_part( 'template-parts/taxonomy/taxonomy', get_post_type() );

                         $html .= ob_get_clean();

                     }
 					/*
 					 * Include the Post-Type-specific template for the content.
 					 * If you want to override this in a child theme, then include a file
 					 * called content-___.php (where ___ is the Post Type name) and that will be used instead.
 					 */

 					endwhile;
                 ?>

                 <div class="bottom-stories md:grid md:grid-cols-3 md:gap-12">
                     <?php echo $html; ?>
                 </div>

                 <div class="pagination">

                     <?php
                     custom_pagination();
                     ?>

                 </div>

             </div>
         </div>
     </div>

 	<?php
 	wp_reset_postdata();
 }

 genesis();
